### ISSUE TITLE
MM with MFT doesn't patch Hitchhiker Storage Container

### ISSUE THREAD

**Issue by KlaasYK** [taraniselsu/TacLifeSupport#68]
I noticed my Hitchhiker Storage Container didn't have any supplies using Modular Fuel Tanks.
This is also the case with the passenger plane parts, which too have no command capabilities.

Apparently only command pods will be patched.

Solution below fixed it for me.

File: TacLifeSupportMFT/MM_AddResourcesMFT.cfg
````
// Add the ModuleFuelTanks to every command pod with crew capacity > 0, unless it already has ModuleFuelTanks.

// Removed ,@MODULE[ModuleCommand] due to Hitchiker Container and Passenger parts lacking supplies
@PART[*]:HAS[!MODULE[ModuleFuelTanks],#CrewCapacity[>0],~RSSROConfig[]]:FOR[TacLifeSupport]:NEEDS[modularFuelTanks|RealFuels]
{
	MODULE
	{
		name = ModuleFuelTanks
		type = LifeSupportAll
		basemass = -1
		volume = 3.549
		@volume *= #$/CrewCapacity$
	}
}
````

**Comment by taraniselsu** [comment]
This was intentional. If you are far enough along in the tech tree to have the Hitchhiker (and similar parts), then you should have unlocked the life support parts and have a big enough VAB to allow the extra parts.

You could argue that the Hitchhiker should have some supplies, but I would prefer to make an explicit exception for it because there are a lot of mod parts that have crew capacity that should *not* have supplies.

**Comment by KlaasYK** [comment]
I was just surprised when I was building a ship using the Hitchhiker there were not that many supplies.

I get your reasoning and understand that making an exception is just a coding/maintainability disaster waiting to happen.

Next time I will just pack more snacks ;)

Keep up the good work.
