### ISSUE TITLE
Hydrogen isn't a waste product! And other brainfarts.

### ISSUE THREAD

**Issue by bashpr0mpt** [taraniselsu/TacLifeSupport#84]
Converting water to oxygen and hydrogen is great. H4 is monopropellant. And oxygen isn't helpful, converting CO2 to straight O doesn't make sense either. You can use that 'waste' hydrogen with the CO2 to make oxygen AND water, even if the hydrogen is reacted into monopropellant it would be feasible with a bit of McGuffin to store waste hydrogen, or rather, to convert 'water' into oxygen AND monopropellant, and to convert monopropellant and CO2 into oxygen AND water. 

Until you allow greenhouses or partner with a group that have habs etc. you shouldn't have a lack of food kill Kerbal's, especially considering they're plants not animals, surely they wouldn't require food to survive and just a bit of sunlight and water could sustain them in a sedentary state where they can't conduct science, perhaps? >_> Just some random brainfart ideas. 

Also; to be brutally honest, I won't touch this until I see plenty of screen shots. There's none anywhere on the forum or the other sites you link to from there. Unless parts fit FLAWLESSLY with the game and have good English language skills incorporated (ie: no engrish tooltips and other stupidity) I generally will never ever consider touching it.

**Comment by taraniselsu** [comment]
Well, the good news is there is no Engrish anywhere! My native language is English as I am from the US.

In regard to your other comments:
1) Hydrogen is not used in the stock game, so I decided not to add yet another resource definition (my mod already adds enough) that would be completely useless unless you use it with another mod. Other mods can easily change the appropriate amount of Waste to Hydrogren or Methane (CH4) with a simple MM script ([helpful information is available](https://docs.google.com/spreadsheets/d/1DkWf210viRSNcV8tvDv30vZ_iACj6GeY1Lf_4JdZYds/edit?usp=sharing)). I had planned to write some compatibility scripts myself that would do that if the other mod(s) were detected, but I did not get to that yet.

2) I disagree with the idea that Kerbals are plants, in spite of their green color. I have always planned to add a greenhouse part, and there are many other mods that provide food generation, so I think the current penalty is fine. Though I have been working on a new version that gives the option to make Kerbals hibernate instead of die when they run out of life support.

3) Sorry that all of my pictures are sorely out of date, but there are two pictures in the forum OP, hidden in the spoiler section. [jfjohnny5 made some new textures for me, so the parts look much better than in that picture](http://forum.kerbalspaceprogram.com/index.php?/topic/37449-105-tac-life-support-v01121-12dec/&page=21#comment-849811). There are also some "Mod Spotlight" videos on Youtube: https://www.youtube.com/watch?v=6jXOo9mozng and https://www.youtube.com/watch?v=eIzG57FmhBQ, plus several more videos where people are using my mod -- like Scott Manley :)
